sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 52
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tE7fYsX5ogU2732vezr
    access-key-secret: AM1KlQF57U5Z20teNVKryokbilrZ3s
    bucket-name: sky-take-out-yyh
  redis:
    host: localhost
    port: 6379
    password: 52
    database: 1
  wechat:
    appid: wxbf347db4a44aaa46
    secret: 2c64a607138bda9f3947a9d4bbc09ad4